### ISSUE TITLE
Paxels aren't pickaxes when breaking amethyst clusters

### ISSUE THREAD

**Issue by TauzentBlitz** [AmyMialeeMods/piercingpaxels#15]
Playing AOF6. Using a drack with fortune 3 (or an unenchanted stone paxel) to break a cluster drops half the shards an unenchanted pickaxe does.

**Comment by AmyMialee** [comment]
That's weird, it sounds like a conflict because I can't see any way this mod would cause that.

**Comment by AmyMialee** [comment]
Not sure if this is still present on 1.20, not planned to fix on old versions.
