### ISSUE TITLE
Items dont drop when mining. (or using right click)

### ISSUE THREAD

**Issue by WhiggaWhite** [AmyMialeeMods/piercingpaxels#22]
When mining individual blocks manually, or using the abilities by holding right click, none of the items drop

With vaccum, only gravel seems to appear in my inventory

**Comment by AmyMialee** [comment]
You have the modlist? and what modloader

**Comment by MEg-Gem** [comment]
**I also encountered this problem.**
**Here are all the mod I have loaded, with HMCL as the initiator**
**Please ignore the Chinese characters  the original MOD name follows the Chinese characters**
![屏幕截图 2023-06-14 224455 png](https://github.com/AmyMialeeMods/piercingpaxels/assets/136614746/13c33711-f7d6-4895-8e14-16b546549c16)
![屏幕截图 2023-06-14 224543](https://github.com/AmyMialeeMods/piercingpaxels/assets/136614746/c65afeac-6fe6-4bcf-8733-82cdb4170629)
![屏幕截图 2023-06-14 224608](https://github.com/AmyMialeeMods/piercingpaxels/assets/136614746/f9c4ec15-87f2-42e0-9b33-ad355d8f67db)

**Comment by Darkerowl** [comment]
same here I can mine dirt or anything that has shovel needs but anything that has pickaxe needs wont go into my inventory at all, it was working just fine at first but now I cannot get it to mine any rock and ore, 

MC:1.20.0 (Fabric)
Mod list: 
![Mods 6_14_2023 2_33_23 PM](https://github.com/AmyMialeeMods/piercingpaxels/assets/19744797/98c3b131-4ed9-41f0-9420-0f9084da1cc7)

**Comment by AmyMialee** [comment]
Very weird, I'll get a fix out soon

**Comment by AmyMialee** [comment]
v1.0.9

**Comment by WhiggaWhite** [comment]
@AmyMialee you're amazing tysm, sorry for not responding with the modlist i went to sleep.

**Comment by AmyMialee** [comment]
No worries, just glad to get it fixed.

**Comment by MEg-Gem** [comment]
That's great! Tysm!

**Comment by MEg-Gem** [comment]
That's great! Thank you!
