### ISSUE TITLE
Piercing Paxels in Ukrainian

### ISSUE THREAD

**Issue by PetroTornado** [AmyMialeeMods/piercingpaxels#23]
Hello, I have completely translated Piercing Paxels into Ukrainian, I would be very happy to have this translation in your cool fashion
[Piercing Paxels.zip](https://github.com/AmyMialeeMods/piercingpaxels/files/11755721/Piercing.Paxels.zip)

**Comment by AmyMialee** [comment]
Hello could you submit this as a Pull Request? It is easier to add and it adds you as a contributor.

**Comment by PetroTornado** [comment]
Hi, I don't know how to use Github very well, if you mean to remove the extraction, I can do it

**Comment by PetroTornado** [comment]
if you are worried that there might be a virus in the zip, I can drop the translation right here

**Comment by AmyMialee** [comment]
I'll add it if you can do a PR with it.
