### ISSUE TITLE
Can't open game with the latest 1.20 version.

### ISSUE THREAD

**Issue by RageQuitAmy** [AmyMialeeMods/piercingpaxels#25]
Piercing Paxels version: piercingpaxels-1.0.9
Architectury API version: architectury-9.0.8-forge
Forge version: 46.0.14

I found this mod yesterday and tried adding it to my modpack. When opening my game, it just crashed with exit code 1 and no crash report. I then tried to figure out what mod was causing it and when I removed this mod, my game started to work. I couldn't see anything in logs about it. I saw the mod was updated today so I thought I would try again, I then had the same issue. I thought I would try with just this mod and again, the same issue happened. Again I can't figure it out in logs. I thought it would be worth submitting an issue as it even happens when trying to use just this one mod with its dependency. I have attached my log below. I am sorry if it is an issue from my end but any help would be appreciated. :)
[latest.log](https://github.com/AmyMialeeMods/piercingpaxels/files/11759412/latest.log)

**Comment by RageQuitAmy** [comment]
😂 Thank you!

**Comment by Aetrnl94** [comment]
I have the same issue, I look forward to being able to use this mod!

**Comment by AmyMialee** [comment]
Should be fixed 1.0.10
