### ISSUE TITLE
Paxel upgrades not working properly on 1.20 Forge

### ISSUE THREAD

**Issue by Mrnar1s** [AmyMialeeMods/piercingpaxels#28]
For some reason, paxel upgrades such as the Auto-smelt, void and silence upgrade do not work at all, and the unbreaking upgrade works the same as a restoration upgrade, very slowly regenerating a tiny bit of durability. I'm playing on forge 1.20 - 46.0.14 on version 1.0.10 of the mod and using version 9.0.8 of Architechtury API.

**Comment by AmyMialee** [comment]
Oh that's annoying. Forge must be breaking the mixins somehow.

**Comment by Mrnar1s** [comment]
Yeah, i've noticed that the current version of forge for 1.20 is very glitchy, i've found many issues with many different mods.

**Comment by AmyMialee** [comment]
> And btw, another issue is the fact that the upgrades that would change the paxels into working like hoes, axes or shovels do not exist on this version.
Yea it's not supported on Forge because forge breaks some stuff in that area.

**Comment by Swedz** [comment]
> Oh that's annoying. Forge must be breaking the mixins somehow.

Do you have any plans to fix this issue? I'm experiencing this issue on latest still.

**Comment by Tander** [comment]
+1,  upgrades not working (tested auto-smelt and vacuum)

**Comment by Zyrille** [comment]
Same issues as the original post, upgrades do not work :( on 1.20.1 forge

**Comment by AmyMialee** [comment]
I'm afraid there are some unfixable issues on the 1.20.1 Forge version, the mod will be moving straight to 1.20.6 so this won't be fixed on that version, but should be fixed in the next update.
