### ISSUE TITLE
Incompatible with tree harvesting mod(s)

### ISSUE THREAD

**Issue by wassupiamYusuf** [AmyMialeeMods/piercingpaxels#30]
Any paxel doesn't work with Fallingtree, tree harvester, etc. (They do work but the paxel doesn't cut down the whole tree because it is not supported.)

**Comment by AmyMialee** [comment]
This depends on the mod, and how they classify an item as an Axe.
Without specific support I'm not sure they will work, but I might consider adding a tree felling upgrade to this mod itself instead.
