### ISSUE TITLE
Unintentional Side effects with Build Wands Mod

### ISSUE THREAD

**Issue by ServerSizeMe** [AmyMialeeMods/piercingpaxels#38]
I'm not entirely sure the specifics but I found that when using Paxels in the Tool Slot of Build Wands this allows for breaking of Bedrock and any Bedrock Like stones from other Mods.

I assume because Paxels are set to be a valid too for all blocks without any exceptions, but Buildwand ignores breaking speed so it can see a Paxel as a valid tool for bedrock and break it.

**Comment by AmyMialee** [comment]
This is more of an issue of buildwand ignoring *all* breaking speed. It should have an exception for blocks that are unbreakable.
Checking if a block is unbreakable at a part of code which checks tags feels off.
